[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
aggregator_v1 = "BPanLhvKwatyLQwSWTbUc3R3VVwsrQWrEeTtzD2DA6TZ"
drift = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./test-scripts/run-ts-mocha.sh"
fulltest = "./test-scripts/run-all-test.sh"
single = "./test-scripts/run-single-test.sh"
lint = "yarn prettier . --write && cargo fmt"

[[test.genesis]]
address = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"
program = "./validator/program/drift-v2.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./validator/program/token-metadata.so"

[[test.genesis]]
address = "2vVPTgsNXh5GtpLBRxxc12BmbyTbgDq6nbmFBRZfzoHY"
program = "./validator/program/token-faucet.so"

[[test.genesis]]
address = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"
program = "./validator/program/mock-pyth.so"